### ISSUE TITLE
Use emacs repo instead of source files?

### ISSUE THREAD

**Issue by mkleehammer** [jimeh/build-emacs-for-macos#33]
Have you considered using a git repo for the source instead of downloading large files for each build?  It seems like it would be easier in the long run to use something like submodules.  Then building a different commit would be as simple as a git checkout.

I realize this is probably one of those things that will be harder than it sounds when you get into it, but it seems like it might make things easier later.

**Comment by jimeh** [comment]
It is something I have considered, main reasons I made the script grab tarballs are:

- Tarballs are around 40-45MB to download, while a fresh clone of Emacs from source is around a 1GB download.
- Using tarballs and extracting them to unique per-commit build directories ensures clean builds.
- Easier to manage a simple tarball download, extract and compile, compared to managing a single git working directory with pulling down latest changes, switching branches, ensuring clean state, etc, which would probably get extra complicated due to the need of applying a few custom patches.
- The script is specifically designed to allow easily building Emacs from any commit, branch, tag, and simply having it grab a tarball feels easier than resetting a git clone accordingly.

That said, the build script operates a single unit right now, and I think it would make sense to separate the steps a bit. This would enable options for providing an existing Emacs source directory managed by the user, and the build script would simply build an Emacs.app within the given source directory without managing downloads, build dirs, or archives.

**Comment by mkleehammer** [comment]
That makes sense.  Especially the ease of starting with a clean build.  I've maintained plenty of scripts that deal with repos and that is a common pain point.
