### ISSUE TITLE
Failed to get commit info about: master

### ISSUE THREAD

**Issue by alisonjoe** [jimeh/build-emacs-for-macos#50]
macos big sur 11.3.1

./build-emacs-for-macos
==> INFO: Fetching info for git ref: master
ERROR: Failed to get commit info about: master

**Comment by jimeh** [comment]
This can happen if you're on a shared connection in a company/school, or behind a VPN, because the lookup happens through GitHub's API, and without an authentication token, API requests are limited to 60 per minute based on source IP.

However if you set the `GITHUB_TOKEN` environment variable to a [GitHub Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token), the build script will make authenticated requests with your token which should resolve this issue for you.

**Comment by alisonjoe** [comment]
Thank you, this is indeed the reason
